dist: trusty
sudo: required
language: python
python:
- '3.6'
services:
- docker
script:
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
- docker pull hasadna/datacity-backend || true
- "./build_docker.sh"
env:
  global:
  - secure: I+P0XEOmoDfjWKcWUtrdfBXJX7Mn1/RZ+ehyN+9/5e6WW4Vtqw8k9In0Q3pYmTVasG6h7QDzIQ6JCExofhBNp3CB4X9GnoPSJUAjihfsbWBsJ27fCNzMo/NQui40zKXDIYDkZZpXzvSaPZoc1aE8RgYmt2Uabc1bm2r96Ti0kUfH04uVkYc6Couc5zfxg5z67Q2sAdMMwJtUM7DEM9j2FQSki7wN9qJ0jbxNcjwhSEkucv4KT/zccnwUMA1vOXrHTuEn9rsRRMOG64rtaD0IHnCgxbuvuBrFddNlwNbryawvtDBTGJyLS4mXiZTEu05mDv2QjyU/+i5gQWdEsKnPdpWyOJOM4RDQQlmgbQLr0Xvp4idwPPQgtrm6Wl8H7F4MDtWwIta1YXKBGMIx63mgVT3a0Hxs3mg10+L9sTJyCQ50Lj+zZjuiVa8sMYGe9ohkTQw1bMuE3zBkWReMCRyH0JhFLml0YpVg+w5bGinIKUyj0H6vW1pFHStjT4EGRC7lusq0hYzIiMV4Lyibe51cK5iZJuqZuMn+TFynPycrz3g9HJzjVzlR1N8XNfx9ShRcpuis1iEb1db/7YYnx9mmxFsJrwRXksqRDE9q+OURJ7iXOJsNfSju3OjCDGqMfzgFeSTfslQRc3g7lyzeCEmGhr3ALWmZt2QXQU5RB3NWndE=
  - secure: eR+SlPbqzGe8ypxZfH5mTY7rHI3ZL9RY104sVQqoyUMuAWh4beX8lw4b2fSFukRwQ8OjFz7o2gOBkOOCM2J7+dPdii6GSseKzhUtFrIlaQADfnHBrdVUPt09Xv/vAXJYPahIXMOOllBVJK00bjxOaZpCsX4+Tljc3KfzoRpaRmKcg0gjr+RKxz7uKArK0GHXn+ZcU0efhEcccLUr2JRv02LS+qQibxujBZKZQo4CiIxf+dLlaKYGPCoTdGMbw+lWUVUP6r6fPBDYzVi/igcJDWfK3T7di3zrZGBN/VdR9AhkA07THVr2dpRyFPvq2A8qIv+JNvufI9xuYEJoP/ynG47RoNIFbMzxYfLJyW4cR/t9v8EOslJmLvz7wIQptuIQ7cyCrbsmV3JI2FlIUV+LtvZ5txC2VxMZsOiQmdWmFBIgKO3Zr94REdwfLOChP+3ER3bQXHjYrM5YQD4u5omvEqRlrL+GlHXJGTRUTFg7nvqzeMcJ+hdQGTZfM7rPiuhTZxjK4+puanocVMZflU4CIiEITa4nQLOhNwAPDSD1+Vi84FwREZ7JdW+45Nx9ijZQSqK1XKTT5pwmbKGi3+IVeSxkgExDi8ky0A6WPRP1khfRQc0PvYz2Re8Yl96UAcrZnxcEDeXFq5JIFnjm58TnSw3CGSeWpJfCMiKZNuJtzDo=
